"""empty message

Revision ID: 73bc969a393a
Revises: 7e27f532b452
Create Date: 2016-01-13 19:49:55.841438

"""

# revision identifiers, used by Alembic.
revision = '73bc969a393a'
down_revision = '7e27f532b452'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_aws_access_id_key', 'projects', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('projects_aws_access_id_key', 'projects', ['aws_access_id'])
    ### end Alembic commands ###
