"""empty message

Revision ID: 9e1f061d7b98
Revises: ef6edca55d1d
Create Date: 2016-01-28 18:12:44.517237

"""

# revision identifiers, used by Alembic.
revision = '9e1f061d7b98'
down_revision = 'ef6edca55d1d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intercom_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Unicode(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_useful_domain', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('project_domain_index', 'intercom_user', ['project_id', 'domain'], unique=False)
    op.create_index('project_user_index', 'intercom_user', ['project_id', 'user_id'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('project_user_index', table_name='intercom_user')
    op.drop_index('project_domain_index', table_name='intercom_user')
    op.drop_table('intercom_user')
    ### end Alembic commands ###
