"""empty message

Revision ID: b680a79956d3
Revises: 080002be4a97
Create Date: 2016-01-09 10:25:44.800004

"""

# revision identifiers, used by Alembic.
revision = 'b680a79956d3'
down_revision = '080002be4a97'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('intercom_webhooks_internal_secret', sa.Unicode(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'intercom_webhooks_internal_secret')
    ### end Alembic commands ###
